name: MANUAL - Single Job With Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      testsToRun:
        description: 'Tests to run'
        required: false
        default: 'all'
      pipelines:
        description: 'Your pipeline'
        type: 'number'
        required: true
        default: '15'
      yourChoiceEdited:
        description: 'Choose an animal'
        type: 'choice'
        required: false
        default: 'parrot'
        options:
          - 'dog'
          - 'cat'
          - 'parrot'
          - 'bird'
      trueOrFalse:
        type: 'boolean'
        default: false
      ALMOCTANE_PARAMETER_SET: 
        type: 'number'
        default: '0'
  workflow_call:
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Log workflow inputs for Octane
      run: |
        echo "execution_parameter:: $(echo '${{ toJson(github.event.inputs) }}' | jq -c .)"
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Run JUnit Tests
      run: mvn test
    - name: Archive JUnit Test Report
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-report
        path: target/surefire-reports/*.xml
